name:                controleDeEstoque
version:             0.1.0.0
github:              "githubuser/controleDeEstoque"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/controleDeEstoque#readme>

dependencies:
- base >= 4.7 && < 5
- process # Call process in system
- bytestring >= 0.10.8.2 # Working with Bytestring
- utf8-string >= 0.3.6 # Working with Word8
- HDBC # Working with Database
- HDBC-mysql >= 0.7.1.0 # Working with MySQL
- MissingH >= 1.4.0.1 # Data.String.Utils and others

library:
  source-dirs: src

executables:
  controleDeEstoque-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - controleDeEstoque

tests:
  controleDeEstoque-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - controleDeEstoque
